# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bitterboyy/Documents/chameleon-chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bitterboyy/Documents/chameleon-chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bitterboyy/Documents/chameleon-chess/CMakeFiles /home/bitterboyy/Documents/chameleon-chess//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bitterboyy/Documents/chameleon-chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chameleon

# Build rule for target.
chameleon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chameleon
.PHONY : chameleon

# fast build rule for target.
chameleon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/build
.PHONY : chameleon/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/main.cpp.s
.PHONY : main.cpp.s

src/bitboard.o: src/bitboard.cpp.o

.PHONY : src/bitboard.o

# target to build an object file
src/bitboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/bitboard.cpp.o
.PHONY : src/bitboard.cpp.o

src/bitboard.i: src/bitboard.cpp.i

.PHONY : src/bitboard.i

# target to preprocess a source file
src/bitboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/bitboard.cpp.i
.PHONY : src/bitboard.cpp.i

src/bitboard.s: src/bitboard.cpp.s

.PHONY : src/bitboard.s

# target to generate assembly for a file
src/bitboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/bitboard.cpp.s
.PHONY : src/bitboard.cpp.s

src/movegen.o: src/movegen.cpp.o

.PHONY : src/movegen.o

# target to build an object file
src/movegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/movegen.cpp.o
.PHONY : src/movegen.cpp.o

src/movegen.i: src/movegen.cpp.i

.PHONY : src/movegen.i

# target to preprocess a source file
src/movegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/movegen.cpp.i
.PHONY : src/movegen.cpp.i

src/movegen.s: src/movegen.cpp.s

.PHONY : src/movegen.s

# target to generate assembly for a file
src/movegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/movegen.cpp.s
.PHONY : src/movegen.cpp.s

src/position.o: src/position.cpp.o

.PHONY : src/position.o

# target to build an object file
src/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/position.cpp.o
.PHONY : src/position.cpp.o

src/position.i: src/position.cpp.i

.PHONY : src/position.i

# target to preprocess a source file
src/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/position.cpp.i
.PHONY : src/position.cpp.i

src/position.s: src/position.cpp.s

.PHONY : src/position.s

# target to generate assembly for a file
src/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/src/position.cpp.s
.PHONY : src/position.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chameleon"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/bitboard.o"
	@echo "... src/bitboard.i"
	@echo "... src/bitboard.s"
	@echo "... src/movegen.o"
	@echo "... src/movegen.i"
	@echo "... src/movegen.s"
	@echo "... src/position.o"
	@echo "... src/position.i"
	@echo "... src/position.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

